[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/anytko/geog510-test/blob/main/lab2_notebook.ipynb)

# This is a notebook for lab 2

## Making arrays using numpy

### Single array

In [11]:
import numpy as np
first_matrix = np.zeros((3))
print(first_matrix)

[0. 0. 0.]


### 2D array

In [12]:
second_matrix = np.array([[1, 2, 3], [3, 4, 5]]) 
print(second_matrix)

[[1 2 3]
 [3 4 5]]


### 3D array

In [13]:
third_matrix = np.array([[[1, 2, 3]], [[3, 4, 5]], [[5, 6, 7]]])
print(third_matrix)

[[[1 2 3]]

 [[3 4 5]]

 [[5 6 7]]]
